#!/usr/bin/env bash
#   dreate /var/run/holbertonscript.pid containing the script PID
#   display"To infinity and beyond" indefinitely
#   display"I hate the kill command" upon receiving a SIGTERM
#   display "Y U no love me?!" upon receiving a SIGINT
#   delete file /var/run/holbertonscript.pid and terminates upon
#  receive a SIGQUIT or SIGTERM

terminator() {
  rm /var/run/holbertonscript.pid
  exit
}

echo "$$" > /var/run/holbertonscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
