#!/usr/bin/env bash
# display "To infinity and beyond" indefinitely
# sleep 2 between iterations
# displays "I am invincible!!!" between each iterations                    


while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM
done
